#pragma once

#include <filesystem>

#include "../IComponent/IUnscalable/IScalable/IUninteractive/OnlyDrawable/Sprite/Sprite.hpp"
#include "../IComponent/IUnscalable/IScalable/IUninteractive/OnlyDrawable/Capsule/Capsule.hpp"
#include "../IComponent/IUnscalable/IScalable/IUninteractive/OnlyDrawable/RoundedRectangle/RoundedRectangle.hpp"
#include "../IComponent/IUnscalable/IScalable/IUninteractive/OnlyDrawable/Video/videoConvert.hpp"
#include "../IComponent/IUnscalable/IScalable/IUninteractive/OnlyDrawable/Video/VideoFromFile/VideoFromFile.hpp"
#include "../IComponent/IUnscalable/IScalable/IUninteractive/Caption/Caption.hpp"
#include "../IComponent/IUnscalable/IScalable/IUninteractive/Bar/Bar.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxBorderHorizontal/BoxBorderHorizontal.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxBorderVertical/BoxBorderVertical.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxBorder/BoxBorder.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxConstRatio/BoxConstRatio.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxConstBezel/BoxConstBezel.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxConstRatioCenter/BoxConstRatioCenter.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxConstBorder/BoxConstBorder.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxPanel/BoxPanel.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxAlternative/BoxAlternative.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxMovableBorder/BoxMovableBorder.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxBackground//BoxBackground.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxShader/BoxShader.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxUninteractive/BoxUninteractive.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxMakePermeable/BoxMakePermeable.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxScroll/BoxScroll.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxSwitch/BoxSwitch.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxTabs/BoxTabs.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxSwitcherTabs/BoxSwitcherTabs.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxConstCenter/BoxConstCenter.hpp"
#include "../IComponent/IUnscalable/IScalable/IInteractive/BaseInteractive/BaseSlider/ConstSlider/ConstSlider.hpp"
#include "../IComponent/IUnscalable/IScalable/IInteractive/BaseInteractive/BaseSlider/Slider/Slider.hpp"
#include "../IComponent/IUnscalable/IScalable/IInteractive/BaseInteractive/BaseButton/Button/Button.hpp"
#include "../IComponent/IUnscalable/IScalable/IInteractive/BaseInteractive/BaseButton/ButtonPanel/ButtonPanel.hpp"
#include "../IComponent/IUnscalable/IScalable/IInteractive/BaseInteractive/Switcher/Switcher.hpp"
#include "../IComponent/IUnscalable/IInteractive/Text/Text.hpp"
#include "../IComponent/IUnscalable/IInteractive/Text/BaseTextBlock/InteractiveTextBlock/InteractiveTextBlock.hpp"
#include "../IComponent/IUnscalable/IInteractive/Text/BaseTextBlock/ObjectTextBlock/ObjectTextBlock.hpp"
#include "../IComponent/IUnscalable/IInteractive/Text/BaseLine/Underline/Underline.hpp"
#include "../IComponent/IUnscalable/IInteractive/Text/BaseLine/StrikeThrough/StrikeThrough.hpp"
#include "../IComponent/IUnscalable/IInteractive/Text/TextInteraction/TextInteraction/TextHotkeyInteraction/TextHotkeyInteraction.hpp"
#include "../IComponent/IUnscalable/IScalable/Interface/Interface.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxSwitchTabs/BaseSwitchTabsEvent/SwitchTabsEvent/SwitchTabsEvent.hpp"
#include "../IComponent/IUnscalable/IScalable/Box/BoxSwitchTabs/BaseSwitchTabsEvent/WhileSwitchTabsEvent/WhileSwitchTabsEvent.hpp"
#include "../SizingAndPositioning/ISizing/ConstSizing/ConstSizing.hpp"
#include "../SizingAndPositioning/ISizing/RelativeNormalSizing/RelativeNormalSizing.hpp"
#include "../SizingAndPositioning/ISizing/RelativeParentSizing/RelativeParentSizing.hpp"
#include "../SizingAndPositioning/ISizing/ParentCoefficientSizing/ParentCoefficientSizing.hpp"
#include "../SizingAndPositioning/ISizing/TargetCoefficientSizing/TargetCoefficientSizing.hpp"
#include "../SizingAndPositioning/ISizing/SmartSizing/SmartSizing.hpp"
#include "../SizingAndPositioning/ISizing/LambdaSizing/LambdaSizing.hpp"
#include "../Interaction/IInteraction/EmptyInteraction/EmptyInteraction.hpp"
#include "../Interaction/IInteraction/MouseInteraction/MouseLambdaInteraction/MouseLambdaInteraction.hpp"
#include "../Interaction/IEvent/KeyEvent/OpenUrlEvent/OpenUrlEvent.hpp"
#include "../Interaction/IEvent/KeyEvent/CloseWindowEvent/CloseWindowEvent.hpp"
#include "../IComponent/IUnscalable/IScalable/IInteractive/BaseInteractive/Switcher/SwitherEvent/SwitcherEvent.hpp"
#include "modules/appendix/yaml-cpp/shared/value/event/set/setSValueEvent.hpp"
#include "../../modules/appendix/yaml-cpp/shared/value/converts/toBool/equals/sConvertToBoolEquals.hpp"
#include "../../modules/appendix/yaml-cpp/shared/value/converts/toBool/greater/sConvertToBoolGreater.hpp"
#include "../../modules/appendix/yaml-cpp/shared/value/converts/toBool/less/sConvertToBoolLess.hpp"
#include "../../modules/appendix/yaml-cpp/shared/value/converts/toBool/lessOrEquals/sConvertToBoolLessOrEquals.hpp"
#include "../../modules/appendix/yaml-cpp/shared/value/converts/toBool/greaterOrEquals/sConvertToBoolGreaterOrEquals.hpp"
#include "../../modules/appendix/yaml-cpp/shared/value/converts/range/general/sConvertRange.hpp"
#include "../Animation/Animator/IAnimatorUnit/Animation/Animation.hpp"
#include "../Animation/Animator/IAnimatorUnit/Prerequisite/Prerequisite.hpp"
#include "../Animation/Animator/IAnimatorUnit/AnimatorUnitMatch/AnimatorUnitMatch.hpp"
#include "../Animation/IChangeVariable/ChangeVariableByStraightLine/ChangeVariableByStraightLine.hpp"
#include "../Animation/IChangeVariable/ChangeVariableByBrokenLine/ChangeVariableByBrokenLine.hpp"
#include "../Animation/IChangeVariable/ChangeVariableBySteppedLine/ChangeVariableBySteppedLine.hpp"
#include "../Animation/IChangeVariable/ChangeVariableBySinusoid/ChangeVariableBySinusoid.hpp"
#include "../Animation/IChangeVariable/ChangeVariableByCurve//ChangeVariableByCurve.hpp"
#include "../Debug/BoxDebug.hpp"

namespace ui {
	void init(int argc = 0, char *argv[] = {}, std::filesystem::path modulesList = {});
	
	void yamlBuilderInit();
}