#pragma once

#include <filesystem>

#include "IE/component/IComponent/IScalable/INonInteractive/OnlyDrawable/Sprite/Sprite.hpp"
#include "IE/component/IComponent/IScalable/INonInteractive/OnlyDrawable/Capsule/Capsule.hpp"
#include "IE/component/IComponent/IScalable/INonInteractive/OnlyDrawable/Capsule/Capsule.hpp"
#include "IE/component/IComponent/IScalable/INonInteractive/OnlyDrawable/RoundedRectangle/RoundedRectangle.hpp"
#include "IE/component/IComponent/IScalable/INonInteractive/OnlyDrawable/Video/video_convert.hpp"
#include "IE/component/IComponent/IScalable/INonInteractive/OnlyDrawable/Video/VideoFromFile/VideoFromFile.hpp"
#include "IE/component/IComponent/IScalable/INonInteractive/Caption/Caption.hpp"
#include "IE/component/IComponent/IScalable/INonInteractive/Bar/Bar.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxBorderHorizontal/BoxBorderHorizontal.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxBorderVertical/BoxBorderVertical.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxBorder/BoxBorder.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxConstRatio/BoxConstRatio.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxConstBezel/BoxConstBezel.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxConstRatioCenter/BoxConstRatioCenter.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxConstBorder/BoxConstBorder.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxPanel/BoxPanel.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxAlternative/BoxAlternative.hpp"
#include "IE/component/IComponent/IScalable/Box/BasicBoxMovableBorder/BasicBoxMovableBorder.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxBackground/BoxBackground.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxShader/BoxShader.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxUninteractive/BoxUninteractive.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxMakePermeable/BoxMakePermeable.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxScroll/BoxScroll.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxSwitch/BoxSwitch.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxTabs/BoxTabs.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxSwitcherTabs/BoxSwitcherTabs.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxConstCenter/BoxConstCenter.hpp"
#include "IE/component/IComponent/IScalable/interactive/BaseSlider/ConstSlider/ConstSlider.hpp"
#include "IE/component/IComponent/IScalable/interactive/BaseSlider/Slider/Slider.hpp"
#include "IE/component/IComponent/IScalable/interactive/BaseButton/Button/Button.hpp"
#include "IE/component/IComponent/IScalable/interactive/BaseButton/ButtonPanel/ButtonPanel.hpp"
#include "IE/component/IComponent/IScalable/interactive/MovableBorder/MovableBorder.hpp"
#include "IE/component/IComponent/IScalable/interactive/Switcher/Switcher.hpp"
#include "IE/component/IComponent/Text/Text.hpp"
#include "IE/component/IComponent/Text/BaseTextBlock/InteractiveTextBlock/InteractiveTextBlock.hpp"
#include "IE/component/IComponent/Text/BaseTextBlock/ObjectTextBlock/ObjectTextBlock.hpp"
#include "IE/component/IComponent/Text/BaseLine/Underline/Underline.hpp"
#include "IE/component/IComponent/Text/BaseLine/StrikeThrough/StrikeThrough.hpp"
#include "IE/component/IComponent/Text/TextAction/TextCopyAction/TextCopyAction.hpp"
#include "IE/component/IComponent/Text/TextAction/TextSelectionAction/TextSelectionAction.hpp"
#include "IE/component/IComponent/IScalable/Interface/Interface.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxSwitchTabs/BaseSwitchTabsAction/SwitchTabsAction/SwitchTabsAction.hpp"
#include "IE/component/IComponent/IScalable/Box/BoxSwitchTabs/BaseSwitchTabsAction/WhileSwitchTabsAction/WhileSwitchTabsAction.hpp"
#include "IE/sizing-positioning/ISizing/ConstSizing/ConstSizing.hpp"
#include "IE/sizing-positioning/ISizing/RelativeNormalSizing/RelativeNormalSizing.hpp"
#include "IE/sizing-positioning/ISizing/RelativeParentSizing/RelativeParentSizing.hpp"
#include "IE/sizing-positioning/ISizing/ParentCoefficientSizing/ParentCoefficientSizing.hpp"
#include "IE/sizing-positioning/ISizing/TargetCoefficientSizing/TargetCoefficientSizing.hpp"
#include "IE/sizing-positioning/ISizing/SmartSizing/SmartSizing.hpp"
#include "IE/sizing-positioning/ISizing/FnSizing/FnSizing.hpp"
#include "IE/interaction/IInteraction/BasicEmptyInteraction/BasicEmptyInteraction.hpp"
#include "IE/interaction/IInteraction/BasicHotkeyInteraction/BasicHotkeyInteraction.hpp"
#include "IE/interaction/IInteraction/BasicAnyPressingInteraction/BasicAnyPressingInteraction.hpp"
#include "IE/interaction/IAction/IBasicActivityAction/BasicOpenUrlAction/BasicOpenUrlAction.hpp"
#include "IE/interaction/IAction/IBasicActivityAction/BasicSetSValueAction/BasicSetSValueAction.hpp"
#include "IE/interaction/IAction/IBasicActivityAction/BasicAddSValueAction/BasicAddSValueAction.hpp"
#include "IE/interaction/IAction/IBasicActivityAction/BasicCloseWindowAction/BasicCloseWindowAction.hpp"
#include "IE/component/IComponent/IScalable/interactive/Switcher/SwitherAction/SwitcherAction.hpp"
#include "IE/shared/ISReadable/readable.hpp"
#include "IE/debug/BoxDebug/BoxDebug.hpp"

namespace ie {
	auto init(int argc = 0, char *argv[] = {}, std::filesystem::path modules_list = {}) -> void;
	
	auto ieml_rttb_init() -> void;
}